//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jMailClient.MyMailServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyMailServer.IMailServer", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMailServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailServer/Login", ReplyAction="http://tempuri.org/IMailServer/LoginResponse")]
        bool Login(string LoginName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailServer/GetUserData", ReplyAction="http://tempuri.org/IMailServer/GetUserDataResponse")]
        string[] GetUserData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailServer/Registration", ReplyAction="http://tempuri.org/IMailServer/RegistrationResponse")]
        bool Registration(string LoginName, string Password, string Name, System.DateTime Birthday, string ImagePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailServer/SendMessage", ReplyAction="http://tempuri.org/IMailServer/SendMessageResponse")]
        bool SendMessage(string[] To, string Subject, string Body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailServer/GetInboxMessages", ReplyAction="http://tempuri.org/IMailServer/GetInboxMessagesResponse")]
        string[][] GetInboxMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailServer/GetSentMessages", ReplyAction="http://tempuri.org/IMailServer/GetSentMessagesResponse")]
        string[][] GetSentMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailServer/Filter", ReplyAction="http://tempuri.org/IMailServer/FilterResponse")]
        string[][] Filter(string Keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailServer/GetContacts", ReplyAction="http://tempuri.org/IMailServer/GetContactsResponse")]
        string[] GetContacts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailServer/DeleteMessage", ReplyAction="http://tempuri.org/IMailServer/DeleteMessageResponse")]
        bool DeleteMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailServer/LogOut", ReplyAction="http://tempuri.org/IMailServer/LogOutResponse")]
        bool LogOut();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailServerChannel : jMailClient.MyMailServer.IMailServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServerClient : System.ServiceModel.ClientBase<jMailClient.MyMailServer.IMailServer>, jMailClient.MyMailServer.IMailServer {
        
        public MailServerClient() {
        }
        
        public MailServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string LoginName, string Password) {
            return base.Channel.Login(LoginName, Password);
        }
        
        public string[] GetUserData() {
            return base.Channel.GetUserData();
        }
        
        public bool Registration(string LoginName, string Password, string Name, System.DateTime Birthday, string ImagePath) {
            return base.Channel.Registration(LoginName, Password, Name, Birthday, ImagePath);
        }
        
        public bool SendMessage(string[] To, string Subject, string Body) {
            return base.Channel.SendMessage(To, Subject, Body);
        }
        
        public string[][] GetInboxMessages() {
            return base.Channel.GetInboxMessages();
        }
        
        public string[][] GetSentMessages() {
            return base.Channel.GetSentMessages();
        }
        
        public string[][] Filter(string Keyword) {
            return base.Channel.Filter(Keyword);
        }
        
        public string[] GetContacts() {
            return base.Channel.GetContacts();
        }
        
        public bool DeleteMessage() {
            return base.Channel.DeleteMessage();
        }
        
        public bool LogOut() {
            return base.Channel.LogOut();
        }
    }
}
